"""
Export utilities — convert analysis results to TXT, Markdown, and JSON.
"""

import json
from datetime import datetime
from typing import Optional


def to_markdown(
    result: dict,
    ocr_text: Optional[str] = None,
    topic: str = "",
    difficulty: str = "",
) -> str:
    """Generate a well-formatted Markdown export."""
    now = datetime.now().strftime("%d %b %Y, %I:%M %p")
    topic_line = f"> **Topic:** {topic}  \n> **Difficulty:** {difficulty}\n\n" if topic else ""

    kw_list = "  ".join(f"`{k}`" for k in result.get("keywords", []))

    questions_md = "\n".join(
        f"{i+1}. {q}" for i, q in enumerate(result.get("questions", []))
    )

    concepts_md = ""
    for c in result.get("key_concepts", []):
        concepts_md += f"**{c['concept']}**\n: {c['definition']}\n\n"

    mnemonics_md = ""
    for m in result.get("mnemonics", []):
        mnemonics_md += f"- 💡 {m}\n"

    ocr_section = ""
    if ocr_text:
        ocr_section = f"""
---

## 📄 Extracted Notes (OCR)

```
{ocr_text}
```
"""

    return f"""# 📚 Study Notes — AI Analysis

> Generated: {now}  
{topic_line}---

## 📝 Summary

{result.get("summary", "")}

---

## 🏷️ Keywords

{kw_list}

---

## ❓ Revision Questions

{questions_md}

---

## 🔑 Key Concepts

{concepts_md if concepts_md else "_No key concepts extracted._"}

## 💡 Memory Aids

{mnemonics_md if mnemonics_md else "_No mnemonics generated._"}
{ocr_section}
---
*Generated by Smart AI Study Assistant*
"""


def to_plain_text(result: dict, ocr_text: Optional[str] = None) -> str:
    """Generate a clean plain text export."""
    now = datetime.now().strftime("%d %b %Y, %I:%M %p")
    lines = [
        "SMART AI STUDY ASSISTANT — ANALYSIS RESULTS",
        f"Generated: {now}",
        "",
        "=" * 60,
        "SUMMARY",
        "=" * 60,
        result.get("summary", ""),
        "",
        "=" * 60,
        "KEYWORDS",
        "=" * 60,
        ", ".join(result.get("keywords", [])),
        "",
        "=" * 60,
        "REVISION QUESTIONS",
        "=" * 60,
    ]
    for i, q in enumerate(result.get("questions", []), 1):
        lines.append(f"  {i}. {q}")

    key_concepts = result.get("key_concepts", [])
    if key_concepts:
        lines += ["", "=" * 60, "KEY CONCEPTS", "=" * 60]
        for c in key_concepts:
            lines.append(f"  • {c['concept']}: {c['definition']}")

    mnemonics = result.get("mnemonics", [])
    if mnemonics:
        lines += ["", "=" * 60, "MEMORY AIDS", "=" * 60]
        for m in mnemonics:
            lines.append(f"  💡 {m}")

    if ocr_text:
        lines += [
            "",
            "=" * 60,
            "EXTRACTED NOTES (OCR)",
            "=" * 60,
            ocr_text,
        ]

    return "\n".join(lines)


def to_json(result: dict, ocr_text: Optional[str] = None) -> str:
    """Serialise the full result as pretty-printed JSON."""
    export = {
        "generated_at": datetime.now().isoformat(),
        "analysis": result,
        "ocr_text": ocr_text or "",
    }
    return json.dumps(export, ensure_ascii=False, indent=2)
